const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const props={SPREADSHEET_ID:'db',ADMIN_EMAILS:'admin@example.com'},tables={},cache=new Map();let reads=0,held=false,forceBusy=false,pdfOutside=false;
function sheet(name){tables[name]??=[];return {getLastRow:()=>tables[name].length,getRange:(row,col,count=1)=>({getValues:()=>{reads++;return tables[name].slice(row-1,row-1+count)},setValues:values=>{values.forEach((v,i)=>tables[name][row-1+i]=v);return{};}}),appendRow:v=>{tables[name].push(v);return{setFrozenRows(){}}},deleteRow:r=>tables[name].splice(r-1,1)};}
const db={getSheetByName:name=>tables[name]?sheet(name):null,insertSheet:sheet,getUrl:()=> 'https://example.test/db'};
const ctx=vm.createContext({console,Date,JSON,Set,Map,Math,Number,Array,String,Error,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]||'',setProperty:(k,v)=>props[k]=v})},SpreadsheetApp:{openById:()=>db},Utilities:{getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>Array.from(crypto.createHash('sha256').update(s).digest())},LockService:{getScriptLock:()=>{let mine=false;return{tryLock:()=>{if(forceBusy||held)return false;held=true;mine=true;return true},hasLock:()=>mine,releaseLock:()=>{held=false;mine=false}}}},CacheService:{getScriptCache:()=>({get:k=>cache.get(k)||null,getAll:keys=>Object.fromEntries(keys.filter(k=>cache.has(k)).map(k=>[k,cache.get(k)])),put:(k,v)=>cache.set(k,v),putAll:values=>Object.entries(values).forEach(([k,v])=>cache.set(k,v))})},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})}});
for(const name of ['Code.gs','Campus.gs','Seed.gs','Asignaciones.gs'])vm.runInContext(fs.readFileSync(__dirname+'/../google-apps-script/'+name,'utf8'),ctx);
for(const name of ['Users','Courses','Enrollments','Attempts','Certificates','Routes','Settings','Auth','Sessions','Invitations'])sheet(name).appendRow(['id','data_json']);
ctx.put_('Settings',{id:'main',company:'Xpanzia Group',portalUrl:'https://example.test/',maxAttempts:5});ctx.put_('Courses',ctx.seedCourse_());ctx.put_('Courses',{...ctx.seedCourse_(),id:'custom',school:'Escuela histórica'});

ctx.actualizarCampusV3();
const users=[{id:'admin',role:'admin',email:'admin@example.com',name:'Admin',consentAt:'yes'}, {id:'alice',role:'student',email:'alice@example.com',name:'Alice',consentAt:'yes'}, {id:'bob',role:'student',email:'bob@example.com',name:'Bob',consentAt:'yes'}];users.forEach(u=>ctx.put_('Users',u));
ctx.user_=token=>{const u=users.find(u=>u.id===token);if(!u)throw Error('Inicia sesión');return u;};
const call=(action,payload={},token='admin')=>ctx.doPost({postData:{contents:JSON.stringify({action,payload,token})}});
const id='gestion-documental';
ctx.put_('Enrollments',{id:'alice_'+id,userId:'alice',courseId:id,completed:[]});
ctx.actualizarXpanziaV4();const snapshot=JSON.stringify(tables);ctx.actualizarXpanziaV4();assert.equal(JSON.stringify(tables),snapshot);
assert.equal(call('catalog',{},'').data.courses.length,0);
assert.equal(call('bootstrap',{},'bob').data.catalog.courses.length,0);
assert.equal(call('catalog',{},'alice').data.courses.length,1);
const visible=call('catalog',{},'alice').data.courses[0];assert(!('assignedUserIds' in visible));assert(!('correct' in visible.quiz[0]));
assert(!call('assignCourse',{courseId:id,userIds:['bob']},'bob').ok);
for(const action of ['enroll','completeLesson','submitQuiz'])assert(!call(action,{courseId:id},'bob').ok);
let c=ctx.get_('Courses',id);assert(call('assignCourse',{courseId:id,revision:c.assignmentRevision,userIds:['bob']}).ok);
assert.equal(call('catalog',{},'alice').data.courses.length,0);assert.equal(call('catalog',{},'bob').data.courses.length,1);
assert(!call('completeLesson',{courseId:id,lessonId:c.lessons[0].id},'alice').ok);
assert(!call('assignCourse',{courseId:id,revision:c.assignmentRevision,userIds:['alice']}).ok,'stale assignment rejected');
assert(!call('assignCourse',{courseId:id,revision:ctx.get_('Courses',id).assignmentRevision,userIds:['missing']}).ok);
c=ctx.get_('Courses',id);{const r=call('saveCourse',{...c,assignedUserIds:['alice']});assert(r.ok,JSON.stringify(r));};assert.deepEqual(Array.from(ctx.get_('Courses',id).assignedUserIds),['bob'],'course edit cannot bypass assignment flow');
assert(call('enroll',{courseId:id},'bob').ok);c=ctx.get_('Courses',id);
for(const lesson of c.lessons)assert(call('completeLesson',{courseId:id,lessonId:lesson.id},'bob').ok);
const req={courseId:id,requestId:crypto.randomUUID(),answers:c.quiz.map(q=>q.correct)};assert(call('submitQuiz',req,'bob').data.passed);assert(call('submitQuiz',req,'bob').data.passed);
assert.equal(ctx.rows_('Attempts').length,1);assert.equal(ctx.rows_('Certificates').length,1);
const cert=ctx.rows_('Certificates')[0];assert(!call('downloadCertificate',{id:cert.id},'alice').ok);
ctx.put_('Routes',{id:'route',published:true,courseIds:[id,'custom']});assert.equal(call('catalog',{},'bob').data.routes.length,0);assert(!call('deleteCourse',{id,updated:c.updated}).ok);
ctx.put_('Routes',{id:'route',published:false,courseIds:['custom']});
assert(!call('deleteCourse',{id,updated:c.updated},'bob').ok);assert(call('deleteCourse',{id,updated:c.updated}).ok);
assert.equal(call('catalog',{},'bob').data.courses.length,0);assert(!call('submitQuiz',req,'bob').ok);assert(!call('saveCourse',c).ok,'deleted course cannot be resurrected');
assert.equal(call('me',{},'bob').data.attempts.length,1);assert.equal(call('me',{},'bob').data.certificates.length,1);assert(call('verifyCertificate',{code:cert.code},'').ok);assert(call('downloadCertificate',{id:cert.id},'bob').data.pending);
assert(!call('adminData',{},'alice').ok);assert(!call('adminData').data.courses.some(x=>x.id===id));
console.log('PASS Xpanzia V4: migration twice, enrolled access preserved, anonymous/student isolation, no assignment/answer leakage, direct request denial, stale edits, user validation, controlled course writes, lesson/quiz completion, retry idempotency, route filtering and deletion guard, soft deletion and historical certificates preserved.');
