const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../web');
const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname;const file=path.join(root,name==='/'?'index.html':name);try{res.setHeader('Content-Type',({'.js':'text/javascript','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg'})[path.extname(file)]||'text/plain');res.end(name==='/config.js'?"window.UC_CONFIG={name:'Campus Xpanzia',company:'Xpanzia Group',demo:true,apiUrl:''};":fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(8772,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8772/');
const login=async role=>{await page.getByRole('button',{name:'Ingresar al campus',exact:true}).click();await page.getByRole('button',{name:role==='admin'?'Soy administrador':'Soy estudiante',exact:true}).click();await page.getByRole('button',{name:'Salir',exact:true}).waitFor();};
const logout=async()=>{await page.getByRole('button',{name:'Salir',exact:true}).click();await page.getByRole('button',{name:'Ingresar al campus',exact:true}).waitFor();};
await login('student');assert.equal(await page.locator('.course').count(),0);await logout();await login('admin');await page.locator('a[href="#admin"]').click();await page.getByRole('button',{name:'Asignaciones',exact:true}).click();await page.getByRole('button',{name:'Añadir usuarios',exact:true}).click();await page.locator('label.assignment-user').filter({hasText:'estudiante@example.com'}).locator('input').check();await page.locator('#assignment-search').fill('nadie');await page.getByRole('button',{name:'Guardar asignaciones',exact:true}).click();await page.getByRole('heading',{name:'Asignación de cursos'}).waitFor();await logout();await login('student');await page.locator('.course').waitFor();assert.equal(await page.locator('.course').count(),1);
await page.locator('a[href="#mis-cursos"]').click();await page.locator('.course').waitFor();
await page.evaluate(async()=>{const c=catalog.courses[0];await api('enroll',{courseId:c.id});for(const l of c.lessons)await api('completeLesson',{courseId:c.id,lessonId:l.id});await api('submitQuiz',{courseId:c.id,requestId:crypto.randomUUID(),answers:[0,1,2,1,3,2,0,1,3,2]});await refresh();});
await page.locator('a[href="#completados"]').click();await page.getByRole('heading',{name:'Cursos completados',exact:true}).waitFor();await page.getByRole('cell',{name:'100%',exact:true}).waitFor();
await logout();await login('admin');await page.locator('a[href="#admin"]').click();await page.getByRole('button',{name:'Asignaciones',exact:true}).click();await page.getByRole('button',{name:'Añadir usuarios',exact:true}).click();await page.locator('label.assignment-user').filter({hasText:'estudiante@example.com'}).locator('input').uncheck();await page.getByRole('button',{name:'Guardar asignaciones',exact:true}).click();await page.getByRole('heading',{name:'Asignación de cursos'}).waitFor();await logout();await login('student');assert.equal(await page.locator('.course').count(),0);await page.goto('http://127.0.0.1:8772/#curso/gestion-documental');await page.waitForFunction(()=>!document.querySelector('[data-action="complete"]'));await page.locator('a[href="#completados"]').click();await page.getByRole('cell',{name:'100%',exact:true}).waitFor();
await logout();await login('admin');await page.locator('a[href="#admin"]').click();await page.getByRole('button',{name:'Cursos',exact:true}).click();await page.getByRole('button',{name:'Duplicar',exact:true}).click();await page.getByRole('button',{name:'Guardar curso',exact:true}).click();await page.getByRole('cell',{name:/\(copia\)/}).waitFor();const row=page.getByRole('row').filter({has:page.getByRole('cell',{name:/\(copia\)/})});page.once('dialog',d=>d.accept());await row.getByRole('button',{name:'Eliminar',exact:true}).click();await page.waitForFunction(()=>!admin.courses.some(c=>c.title.includes('(copia)')));
await page.getByRole('button',{name:'Asignaciones',exact:true}).click();await page.getByRole('button',{name:'Añadir usuarios',exact:true}).click();await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS UI: assignment selection/search, save, student isolation, assigned courses, completion history after removal, duplication without access, delete and mobile.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exit(1)});
