const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const http=require('http'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'../web');
const previews=path.resolve(__dirname,'../previews');fs.mkdirSync(previews,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(path.basename(file)==='config.js'?fs.readFileSync(file,'utf8').replace('demo: false','demo: true'):fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
(async()=>{
 await new Promise(r=>server.listen(8765,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER:',e.message);});
 await page.goto('http://127.0.0.1:8765');await page.getByRole('heading',{name:'Tu talento, en expansión.'}).waitFor();await page.screenshot({path:path.join(previews,'campus-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Ingresar al campus',exact:true}).click();await page.getByRole('button',{name:'Soy estudiante',exact:true}).click();await page.getByRole('button',{name:'Salir',exact:true}).waitFor();
 await page.locator('a[href="#curso/gestion-documental"]').first().click();await page.getByRole('button',{name:'Inscribirme y empezar',exact:true}).click();
 await page.evaluate(()=>{window.qaCalls=[];const original=UC_DEMO.call.bind(UC_DEMO);UC_DEMO.call=async(a,p)=>{window.qaCalls.push(a);if(a==='completeLesson'&&window.qaFail)throw Error('Fallo de conexión simulado');return original(a,p);};window.qaFail=true;});
 await page.getByRole('button',{name:'Marcar como completada →',exact:true}).click();
 await page.getByText('Fallo de conexión simulado',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>me.enrollments[0].completed.length),0);
 await page.evaluate(()=>{window.qaFail=false;window.qaCalls=[];});
 for(let i=0;i<3;i++){await page.getByRole('button',{name:'Marcar como completada →',exact:true}).click();await page.waitForFunction(n=>me.enrollments[0].completed.length===n&&lessonIndex===n,i+1);}
 assert.deepEqual(await page.evaluate(()=>window.qaCalls),['completeLesson','completeLesson','completeLesson']);
 await page.evaluate(()=>{catalog.courses[0].lessons[0].url='https://youtu.be/dQw4w9WgXcQ';});
 await page.locator('.lesson-nav [data-index="0"]').click();
 assert.equal(await page.locator('.resource-viewer iframe').getAttribute('src'),'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ');
 await page.getByRole('button',{name:'Continuar →',exact:true}).click();
 assert.equal((await page.evaluate(()=>window.qaCalls)).length,3);
 await page.getByRole('button',{name:'◇ Evaluación final',exact:true}).click();
 assert.equal(await page.evaluate(()=>resourceSource('javascript:alert(1)')),null);
 assert.equal(await page.evaluate(()=>resourceSource('https://youtube.com.evil.test/watch?v=dQw4w9WgXcQ')),null);
 assert.equal(await page.evaluate(()=>resourceSource('https://drive.google.com/file/d/abc123/view?resourcekey=key').url),'https://drive.google.com/file/d/abc123/preview?resourcekey=key');
 for(const [ext,kind] of [['mp4','video'],['mp3','audio'],['jpg','image'],['pdf','frame']])assert.equal(await page.evaluate(ext=>resourceSource('https://example.com/file.'+ext).kind,ext),kind);

 await page.locator('#quiz-form').waitFor();
 for(let i=0;i<10;i++)await page.locator(`[name="q${i}"][value="0"]`).check();
 await page.getByRole('button',{name:'Enviar evaluación',exact:true}).click();await page.getByText('Un intento más para seguir aprendiendo.').waitFor();
 await page.getByRole('button',{name:'Repasar el curso',exact:true}).click();await page.getByRole('button',{name:'◇ Evaluación final',exact:true}).click();
 const answers=[0,1,2,1,3,2,0,1,3,2];for(let i=0;i<answers.length;i++)await page.locator(`[name="q${i}"][value="${answers[i]}"]`).check();
 await page.getByRole('button',{name:'Enviar evaluación',exact:true}).click();await page.getByRole('heading',{name:'¡Curso aprobado!',exact:true}).waitFor();
 await page.getByRole('link',{name:'Ver mis certificados →',exact:true}).click();await page.locator('.cert').first().waitFor();assert.equal(await page.locator('.cert').count(),2);await page.locator('.cert a').first().click();await page.getByText('DEMOSTRACIÓN SIN VALIDEZ',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Salir',exact:true}).click();await page.getByRole('button',{name:'Ingresar al campus',exact:true}).click();await page.getByRole('button',{name:'Soy administrador',exact:true}).click();await page.locator('a[href="#admin"]').click();await page.getByRole('heading',{name:'Administración',exact:true}).waitFor();await page.locator('#report-content .stat').first().waitFor();
 await page.getByRole('button',{name:'Cursos',exact:true}).click();await page.getByRole('button',{name:'+ Crear curso',exact:true}).click();
 await page.locator('#title').fill('Curso de prueba QA');await page.locator('#description').fill('Descripción para validar el editor');await page.locator('#lt0').fill('Lección QA');await page.locator('#lb0').fill('Contenido de prueba.');await page.locator('#qt0').fill('Pregunta de prueba');for(let j=0;j<4;j++)await page.locator('#qo0_'+j).fill('Opción '+j);await page.locator('[name="published"]').check();
 await page.getByRole('button',{name:'Guardar curso',exact:true}).click();await page.getByRole('cell',{name:'Curso de prueba QA',exact:true}).waitFor();
 await page.getByRole('button',{name:'Rutas',exact:true}).click();await page.getByRole('button',{name:'+ Crear ruta',exact:true}).click();await page.locator('#title').fill('Ruta QA');await page.locator('[name="courseIds"]').first().check();await page.getByRole('button',{name:'Guardar ruta',exact:true}).click();await page.getByRole('cell',{name:'Ruta QA',exact:true}).waitFor();
 await page.getByRole('button',{name:'Personas',exact:true}).click();await page.locator('#emails').fill('prueba@example.com');await page.getByRole('button',{name:'Autorizar correos',exact:true}).click();await page.getByText('1 correos autorizados individualmente.').waitFor();
 await page.getByRole('button',{name:'Certificados',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Revocar',exact:true}).first().click();await page.getByText('Revocado',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Indicadores',exact:true}).click();await page.locator('#report-content .stat').first().waitFor();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Descargar CSV',exact:true}).click();assert.match((await dl).suggestedFilename(),/Seguimiento/);
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8765/#inicio');await page.getByRole('heading',{name:/Hola,/}).waitFor();await page.waitForTimeout(300);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile horizontal overflow');await page.getByRole('button',{name:'Abrir menú'}).click();await page.locator('a[href="#oferta"]').first().click();await page.locator('#course-search').fill('inexistente');await page.getByRole('heading',{name:'Todavía no hay cursos aquí.'}).waitFor();
 const mobile=await browser.newPage({viewport:{width:390,height:844}});await mobile.goto('http://127.0.0.1:8765/');await mobile.getByRole('heading',{name:'Tu talento, en expansión.'}).waitFor();await mobile.waitForTimeout(300);await mobile.screenshot({path:path.join(previews,'campus-mobile.png'),fullPage:true});await mobile.close();
 assert.deepEqual(errors,[]);console.log('PASS: desktop + mobile, login, enrollment, failure/retry, approval, course/route certificates, verification, admin editor, route editor, authorization, revocation, CSV, search.');await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1)});
