const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let saved=null,fail=false,closed=0;const properties={CERTIFICATE_FOLDER_ID:'folder',CERTIFICATE_PREMIUM_TEMPLATE_ID:'template'};
const shapes=[],files=new Map();const style=new Proxy({},{get:()=>()=>style});
function shape(){let title='',value='';const text={setText:x=>{value=x;return text;},getTextStyle:()=>style,getParagraphStyle:()=>style};return {setTitle:x=>{title=x},getTitle:()=>title,getText:()=>text,setContentAlignment:()=>{},getFill:()=>style,getBorder:()=>({getLineFill:()=>style,setWeight:()=>{}}),getValue:()=>value};}
const slide={getPageElements:()=>[],insertImage:()=>{},insertTextBox:()=>{const s=shape();shapes.push(s);return s;},insertShape:()=>shape(),insertLine:()=>({getLineFill:()=>style,setWeight:()=>{}}),getShapes:()=>shapes};
const deck={getId:()=> 'template',getSlides:()=>[slide],getPageWidth:()=>720,getPageHeight:()=>405,saveAndClose:()=>{closed++;}};
const pdf={setName:()=>pdf};function file(id){if(!files.has(id))files.set(id,{id,trashed:false,getId:()=>id,getUrl:()=> 'https://example.com/'+id,moveTo:()=>{},setTrashed:v=>{files.get(id).trashed=v},makeCopy:()=>file('copy'),getAs:()=>pdf});return files.get(id);}
const ctx=vm.createContext({SlidesApp:{create:()=>deck,openById:()=>deck,ShapeType:{ELLIPSE:'ellipse'},ParagraphAlignment:{CENTER:'center'},ContentAlignment:{MIDDLE:'middle'},LineCategory:{STRAIGHT:'straight'}},DriveApp:{getFileById:file,getFolderById:()=>({createFile:()=>file('pdf')})},PropertiesService:{getScriptProperties:()=>({setProperty:(k,v)=>{properties[k]=v}})},Utilities:{base64Decode:()=>[],newBlob:()=>({})},MimeType:{PDF:'pdf'},prop_:k=>properties[k]||'',resetRequest_:()=>{},need_:(yes,msg)=>{if(!yes)throw Error(msg)},settings_:()=>({company:'Company'}),now_:()=> '2026-09-29',put_:(table,value)=>{if(fail)throw Error('write failed');saved=structuredClone(value)},console:{log:()=>{}}});
vm.runInContext(fs.readFileSync(__dirname+'/../google-apps-script/Certificate.gs','utf8'),ctx);
ctx.prepararCertificadoPremium();assert.equal(shapes.length,14);
const c={id:'id',name:'Persona QA',title:'Curso QA',company:'Empresa QA',signer:'Responsable',hours:2,date:'2026-09-29',code:'UC-QA',portalUrl:'https://example.com/',mailStatus:'sent',fileId:'old'};
ctx.generatePremiumPdf_(c);assert.equal(saved.designVersion,'xpanzia-2-transparent');assert.equal(saved.mailStatus,'sent');assert.equal(c.fileId,'pdf');assert(files.get('copy').trashed);assert.equal(shapes.find(s=>s.getTitle()==='uc_name').getValue(),'Persona QA');
fail=true;const failed={...c,fileId:'previous'};assert.throws(()=>ctx.generatePremiumPdf_(failed),/write failed/);assert.equal(failed.fileId,'previous');assert(files.get('pdf').trashed);assert(closed>=3);
console.log('PASS: Slides template fields, PDF registration, unchanged mail status, temp cleanup and failed-save rollback (mocked Google services).');
