'use strict';
document.title=UC_CONFIG.name||'Universidad Corporativa';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const schools=[['Liderazgo','◎'],['Calidad','◇'],['SST','✚'],['Servicio','♡'],['Procesos','▤'],['Cultura organizacional','◈']];
const nav=[['inicio','⌂','Inicio'],['oferta','▦','Oferta académica'],['mis-cursos','▤','Mis cursos'],['rutas','⌁','Rutas de aprendizaje'],['certificados','♧','Certificaciones'],['biblioteca','▥','Biblioteca'],['ayuda','?','Preguntas frecuentes']];
let catalog={courses:[],routes:[],settings:{}}, me=null, token=sessionStorage.getItem('xpanzia_token_v1')||'', admin=null, adminTab='resumen', editing=null, filterSchool='', lessonIndex=0, lastCourse='', loadVersion=0;
const date=s=>s?new Date(s).toLocaleDateString('es-CO',{year:'numeric',month:'short',day:'numeric'}):'—';
const btn=(label,action,attrs='',cls='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const tag=(s,cls='')=>`<span class="tag ${cls}">${esc(s)}</span>`;
const field=(name,label,value='',type='text',extra='')=>`<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;
const textField=(name,label,value='',extra='')=>`<div class="field"><label for="${name}">${label}</label><textarea id="${name}" name="${name}" ${extra}>${esc(value)}</textarea></div>`;
const heading=(eye,title,sub='',action='')=>`<div class="intro"><div><div class="eyebrow">${eye}</div><h1>${title}</h1>${sub?`<p class="muted">${sub}</p>`:''}</div>${action}</div>`;
const empty=(title,body,action='')=>`<div class="empty"><h3>${title}</h3><p>${body}</p>${action}</div>`;
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',5000);}
async function requestApi(action,payload={}){if(UC_CONFIG.demo)return UC_DEMO.call(action,payload);if(!/^https:\/\/script.google.com\/macros\/s\/[^/]+\/exec$/.test(UC_CONFIG.apiUrl))throw Error('El campus aún no está conectado. El administrador debe configurar la dirección de Apps Script.');let response;try{response=await fetch(UC_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},redirect:'follow',body:JSON.stringify({action,payload,token}),signal:AbortSignal.timeout(65000)});}catch{throw Error('No se pudo confirmar la operación. Revisa tu conexión y vuelve a intentar. Si estabas enviando una evaluación, no cierres esta página.');}if(!response.ok)throw Error('El servidor no pudo atender la solicitud. Intenta nuevamente.');let result;try{result=await response.json();}catch{throw Error('Google no devolvió una respuesta válida. Revisa el acceso público de la implementación de Apps Script.');}if(!result.ok)throw Error(result.error||'No fue posible completar la operación.');return result.data;}
let pendingRequests=0;
async function api(action,payload={}){
 let status=$('#network-status');if(!status){status=document.createElement('div');status.id='network-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');document.body.append(status);}
 pendingRequests++;status.hidden=false;status.textContent='Procesando…';
 try{return await requestApi(action,payload);}finally{pendingRequests--;status.hidden=pendingRequests===0;}
}
function upsert(list,item){const i=list.findIndex(x=>x.id===item.id);if(i<0)list.push(item);else list[i]=item;}
async function refreshProfile(){if(token){try{me=await api('me');}catch(e){if(/sesión|inactivo|Inicia/i.test(e.message)){me=null;token='';sessionStorage.removeItem('xpanzia_token_v1');}else throw e;}}}
async function refresh(){await Promise.all([api('catalog').then(data=>{catalog=data;}),refreshProfile()]);chrome();}
function chrome(){const section=location.hash.slice(1).split('/')[0]||'inicio';$('#navigation').innerHTML=nav.concat(me?.user.role==='admin'?[['admin','⚙','Administración']]:[]).map(([id,icon,label])=>`<a href="#${id}" class="${section===id?'active':''}"><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('');$('#section-name').textContent=nav.find(n=>n[0]===section)?.[2]||({curso:'Mi aula',perfil:'Mi perfil',admin:'Administración',verificar:'Verificar certificado'}[section]||'Campus');$('#account').innerHTML=me?`<a class="row" href="#perfil"><span class="avatar">${esc(me.user.name?.slice(0,2).toUpperCase()||'UC')}</span><span class="account-name">${esc(me.user.name?.split(' ')[0]||me.user.email)}</span></a>${btn('Salir','logout','','secondary small')}`:btn('Ingresar al campus','login','','small');$('#mode').innerHTML=UC_CONFIG.demo?'<span class="demo-label">MODO DEMOSTRACIÓN</span>':'<span class="demo-label">CAMPUS VIRTUAL</span>';$('#footer-brand').textContent=catalog.settings.company||UC_CONFIG.company;}
function enrollment(c){return me?.enrollments.find(e=>e.courseId===c.id);}
function passed(id){return !!me?.attempts.some(a=>a.courseId===id&&a.passed);}
function percent(c){const e=enrollment(c);return Math.round((e?.completed.filter(id=>c.lessons.some(l=>l.id===id)).length||0)/c.lessons.length*100);}
function courseCard(c,i=0){const enrolled=enrollment(c),p=percent(c);return `<article class="course"><div class="course-cover" data-school="${esc(c.school)}"><div>${tag(c.school)}<p class="small" style="margin:12px 0 0">APRENDIZAJE A TU RITMO</p></div><span class="cover-number">${String(i+1).padStart(2,'0')}</span></div><div class="course-body"><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="course-meta"><span>◷ ${c.hours} horas</span><span>◈ ${esc(c.level)}</span></div>${enrolled?`<div class="progress" aria-label="${p}% de lecciones completadas"><span style="width:${p}%"></span></div>`:''}<div class="course-bottom">${tag(passed(c.id)?'Aprobado':enrolled?`${p}% de contenido`:'Con certificado',passed(c.id)?'green':'')}<a class="btn small" href="#curso/${encodeURIComponent(c.id)}">${enrolled?'Continuar':'Ver curso'} →</a></div></div></article>`;}
function home(){const enrolled=catalog.courses.filter(c=>enrollment(c));const featured=enrolled.find(c=>!passed(c.id))||catalog.courses[0];return heading('XPANZIA GROUP / UNIVERSIDAD CORPORATIVA',me?`Hola, ${esc(me.user.name?.split(' ')[0]||'bienvenido')}.`:'Tu talento, en expansión.','Formación que te acompaña en cada paso de tu desarrollo profesional.')+`<section class="hero"><div><div class="eyebrow">${enrolled.length?'CONTINÚA TU APRENDIZAJE':'EMPIEZA A EXPLORAR'}</div><h2>${featured?esc(featured.title):'Conocimiento que crece contigo.'}</h2><p>${featured?'Convierte lo que aprendes en mejores decisiones para tu día a día. Avanza a tu ritmo y demuestra tus conocimientos.':'Explora las escuelas. Pronto encontrarás nuevas oportunidades de formación.'}</p><a class="btn gold" href="${featured?'#curso/'+featured.id:'#oferta'}">${enrolled.length?'Volver a mi aula':'Explorar mi primer curso'} <span>↗</span></a></div><div class="hero-summary"><span class="hero-emblem" aria-hidden="true">X</span><div><strong>06</strong><span>escuelas de formación</span></div><div class="mini"><strong>${String(catalog.courses.length).padStart(2,'0')}</strong><span>cursos disponibles</span></div></div></section><div class="stats">${stat('Cursos inscritos',me?.enrollments.length||0,'▤')}${stat('Cursos aprobados',new Set(me?.attempts.filter(a=>a.passed).map(a=>a.courseId)||[]).size,'✓')}${stat('Mis certificados',me?.certificates.filter(c=>!c.revoked).length||0,'♧')}${stat('Horas aprobadas',catalog.courses.filter(c=>passed(c.id)).reduce((n,c)=>n+c.hours,0),'◷')}</div><div class="section-head"><h2>Explora nuestras escuelas</h2><a class="btn link" href="#oferta">Ver oferta completa ↗</a></div><div class="schools">${schools.map(([s,icon])=>`<button class="school" data-action="school" data-school="${s}"><span class="school-symbol">${icon}</span><strong>${s}</strong><small>${catalog.courses.filter(c=>c.school===s).length} ${catalog.courses.filter(c=>c.school===s).length===1?'curso':'cursos'}</small></button>`).join('')}</div><div class="section-head"><h2>${enrolled.length?'Tu aprendizaje en marcha':'Una nueva habilidad te espera'}</h2><a class="btn link" href="#rutas">Conoce las rutas ↗</a></div><div class="grid">${(enrolled.length?enrolled:catalog.courses).slice(0,3).map(courseCard).join('')}</div>`;}
function stat(label,value,icon){return `<div class="stat"><div><small>${label}</small><b>${value}</b></div><span class="stat-icon">${icon}</span></div>`;}
function offer(){return heading('OFERTA ACADÉMICA','Elige qué quieres aprender.','Encuentra tu curso por escuela o por tema.')+`<div class="filters"><input id="course-search" aria-label="Buscar cursos" placeholder="Buscar un curso…"><select id="school-filter" aria-label="Filtrar por escuela"><option value="">Todas las escuelas</option>${schools.map(([s])=>`<option ${s===filterSchool?'selected':''}>${s}</option>`).join('')}</select></div><div id="course-results" class="grid"></div>`;}
function filterCourses(){const term=$('#course-search')?.value.toLowerCase()||'';filterSchool=$('#school-filter')?.value||'';const list=catalog.courses.filter(c=>(!filterSchool||c.school===filterSchool)&&(c.title+' '+c.description).toLowerCase().includes(term));$('#course-results').innerHTML=list.length?list.map(courseCard).join(''):empty('Todavía no hay cursos aquí.','Prueba otra escuela o cambia tu búsqueda.');}
function requireLogin(){return heading('TU ESPACIO PERSONAL','Aprende con tu cuenta.')+empty('Ingresa para guardar tu avance.','Podrás retomar tus cursos y consultar tus certificaciones.',btn('Ingresar al campus','login'));}
function myCourses(){if(!me)return requireLogin();const list=catalog.courses.filter(c=>enrollment(c));return heading('MI APRENDIZAJE','Cada paso cuenta.','Retoma tus lecciones y revisa tus resultados.')+(list.length?`<div class="grid">${list.map(courseCard).join('')}</div>`:empty('Aún no tienes cursos inscritos.','Elige uno de la oferta académica para comenzar.','<a class="btn" href="#oferta">Explorar cursos</a>'))+(me.attempts.length?`<div class="section-head"><h2>Historial de evaluaciones</h2></div>${table(['Curso','Fecha','Nota','Resultado'],me.attempts.slice().reverse().map(a=>[esc(a.courseTitle||a.courseId),date(a.date),a.score+'%',tag(a.passed?'Aprobado':'Por mejorar',a.passed?'green':'gold')]))}`:'');}
function coursePage(id){const c=catalog.courses.find(c=>c.id===id);if(!c)return empty('Curso no disponible.','Puede haberse retirado de la oferta.','<a class="btn" href="#oferta">Volver a la oferta</a>');if(lastCourse!==id){lessonIndex=0;lastCourse=id;}const e=enrollment(c),isPassed=passed(id);let content=heading(esc(c.school),esc(c.title),`${c.hours} horas · ${esc(c.level)} · Aprobación desde ${c.passScore}%`,'<a class="btn secondary" href="#oferta">← Oferta</a>');if(!e)return content+`<div class="panel"><p>${esc(c.description)}</p><h2>Tu recorrido</h2>${c.lessons.map((l,i)=>`<div class="route-step"><b>${i+1}</b><span>${esc(l.title)}</span>${tag(l.type)}</div>`).join('')}<div class="route-step"><b>✓</b><span>Evaluación final · ${c.quiz.length} preguntas</span></div><div class="dialog-actions">${btn(me?'Inscribirme y empezar':'Ingresar e inscribirme','enroll',`data-id="${esc(id)}"`)}</div></div>`;
 const l=c.lessons[lessonIndex];content+=`<div class="course-layout"><aside class="lesson-nav"><h3>Contenido del curso</h3><div class="progress"><span style="width:${percent(c)}%"></span></div><p class="small muted">${percent(c)}% de lecciones completadas</p>${c.lessons.map((l,i)=>`<button data-action="lesson" data-index="${i}" class="${lessonIndex===i?'active':''}">${e.completed.includes(l.id)?'✓':'○'} ${esc(l.title)}</button>`).join('')}<button data-action="lesson" data-index="${c.lessons.length}" class="${!l?'active':''}">◇ Evaluación final</button>${isPassed?tag('Curso aprobado','green'):''}</aside><section>`;
 if(l){content+=`<article class="panel">${tag(l.type)}<h2 style="margin-top:20px">${esc(l.title)}</h2><div class="reading">${esc(l.body)}</div>${l.url?resourceViewer(l.url,l.title):''}<div class="lesson-actions">${btn(lessonIndex?'← Anterior':'Volver a mis cursos',lessonIndex?'previous':'mycourses','','secondary')}${btn(e.completed.includes(l.id)?'Continuar →':'Marcar como completada →','complete',`data-course="${esc(id)}" data-lesson="${esc(l.id)}"`)}</div></article>`;}else if(isPassed){const a=me.attempts.find(x=>x.courseId===id&&x.passed);content+=`<div class="panel" style="text-align:center">${tag('Objetivo alcanzado','green')}<h2 style="margin-top:22px">¡Curso aprobado!</h2><div class="score">${a.score}%</div><p>Tu certificado ya está registrado. ${UC_CONFIG.demo?'Esta es una aprobación de demostración.':'Recibirás el PDF por correo una vez se procese el envío.'}</p><a class="btn" href="#certificados">Ver mis certificados →</a></div>`;}else if(percent(c)<100){content+=empty('Te faltan algunas lecciones.','Completa el contenido del curso para habilitar la evaluación.');}else{content+=`<div class="panel"><h2>Demuestra lo que aprendiste.</h2><p class="muted">${c.quiz.length} preguntas · Nota mínima ${c.passScore}% · Hasta ${catalog.settings.maxAttempts} intentos al día (UTC).</p><form id="quiz-form" data-course="${esc(id)}" data-request="${crypto.randomUUID()}">${c.quiz.map((q,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${esc(q.text)}</legend>${q.options.map((o,j)=>`<label><input required type="radio" name="q${i}" value="${j}"><span>${esc(o)}</span></label>`).join('')}</fieldset>`).join('')}<p class="error" id="quiz-error" role="alert"></p><button class="btn" type="submit">Enviar evaluación</button></form></div>`;}return content+'</section></div>';}
function safeUrl(url){try{const u=new URL(url);return u.protocol==='https:'?esc(u.href):'#';}catch{return '#';}}
function certificates(){if(!me)return requireLogin();return heading('MIS LOGROS','Lo que aprendes deja huella.','Consulta y descarga tus certificados.','<a class="btn secondary" href="#verificar">Verificar código ↗</a>')+(UC_CONFIG.demo?'<div class="notice">Modo demostración: los certificados no tienen validez institucional y no se envían correos.</div>':'')+(me.certificates.length?`<div class="grid">${me.certificates.map(c=>`<article class="panel cert"><div class="cert-icon">♧</div>${tag(c.revoked?'Revocado':c.routeId?'Ruta completada':'Curso aprobado',c.revoked?'red':'green')}<h3>${esc(c.title)}</h3><p class="muted small">${date(c.date)} · ${c.hours} horas</p><code>${esc(c.code)}</code><p class="small muted" style="margin-top:14px">${c.mailStatus==='sent'?'Enviado a tu correo':c.mailStatus==='demo'?'Certificado de demostración':c.mailStatus==='error'?'Envío pendiente de reintento':'Preparando envío por correo'}</p><div class="row">${btn('Vista previa','preview-certificate',`data-id="${esc(c.id)}"`,'secondary small')}${c.revoked?'':btn(UC_CONFIG.demo?'Ver certificado':'Descargar PDF','download',`data-id="${esc(c.id)}"`,'small')}<a class="btn link" href="#verificar/${encodeURIComponent(c.code)}">Verificar ↗</a></div></article>`).join('')}</div>`:empty('Tu primer certificado te espera.','Aprueba un curso para recibir tu certificado.','<a class="btn" href="#oferta">Explorar cursos</a>'));}
function routes(){return heading('RUTAS DE APRENDIZAJE','Un propósito. Varios pasos.','Completa todos los cursos de una ruta y recibe su certificación.')+(catalog.routes.length?`<div class="grid">${catalog.routes.map(r=>{const n=r.courseIds.filter(passed).length;return `<article class="panel"><div class="eyebrow">RUTA DE FORMACIÓN</div><h2>${esc(r.title)}</h2><p class="muted">${esc(r.description)}</p>${r.courseIds.map((id,i)=>{const c=catalog.courses.find(x=>x.id===id);return `<div class="route-step"><b>${passed(id)?'✓':i+1}</b>${c?`<a href="#curso/${encodeURIComponent(id)}">${esc(c.title)}</a>`:'<span>Curso no disponible temporalmente</span>'}</div>`;}).join('')}<div class="progress"><span style="width:${n/r.courseIds.length*100}%"></span></div><p class="small muted">${n} de ${r.courseIds.length} cursos aprobados</p>${n===r.courseIds.length?'<a class="btn" href="#certificados">Ver mi logro</a>':''}</article>`;}).join('')}</div>`:empty('Estamos preparando nuevas rutas.','Mientras tanto, puedes avanzar en cursos individuales.'));}
function library(){const lessons=catalog.courses.flatMap(c=>c.lessons.map(l=>({...l,course:c})));return heading('BIBLIOTECA','Conocimiento a la mano.','Lecturas y recursos de los cursos disponibles.')+`<div class="filters"><input id="library-search" placeholder="Buscar un recurso…" aria-label="Buscar recursos"></div><div class="grid" id="library-results">${lessons.map(l=>`<article class="panel resource" data-search="${esc((l.title+' '+l.course.title).toLowerCase())}">${tag(l.type)}<h3 style="margin-top:18px">${esc(l.title)}</h3><p class="small muted">${esc(l.course.title)}</p>${l.url?`<button class="btn secondary small" data-action="preview-resource" data-course="${esc(l.course.id)}" data-lesson="${esc(l.id)}">Ver aquí</button>`:`<a class="btn secondary small" href="#curso/${encodeURIComponent(l.course.id)}">Ir al curso →</a>`}</article>`).join('')}</div><p id="library-empty" class="muted" hidden>No se encontraron recursos.</p>`;}
function verifyPage(code=''){return heading('VERIFICACIÓN PÚBLICA','Un logro que puedes comprobar.','Consulta la autenticidad de un certificado mediante su código.')+`<div class="panel" style="max-width:720px"><form id="verify-form">${field('code','Código de certificado',code,'text','required maxlength="80" placeholder="UC-2026-…"')}<button class="btn">Verificar certificado</button><p class="small muted" style="margin-top:18px">La consulta muestra titular, curso, fecha y estado. No muestra documento ni correo.</p></form></div><div id="verification-result" aria-live="polite"></div>`;}
function profile(){if(!me)return requireLogin();const u=me.user;return heading('MI PERFIL','Tus datos, siempre al día.','Tu nombre aparecerá en los próximos certificados que obtengas.')+`<div class="panel editor-width"><form id="profile-form"><div class="form-grid">${field('name','Nombre completo',u.name,'text','required maxlength="150" autocomplete="name"')}${field('document','Número de identificación',u.document,'text','required maxlength="30"')}${field('company','Empresa',u.company,'text','required maxlength="150"')}${field('area','Área',u.area,'text','required maxlength="150"')}${field('position','Cargo',u.position,'text','required maxlength="150"')}${field('city','Ciudad',u.city,'text','required maxlength="150"')}</div><p class="muted">Correo de acceso: ${esc(u.email)}</p><details><summary>Tratamiento de datos personales</summary><p>${esc(catalog.settings.privacy)}</p></details><label style="margin-top:20px"><input type="checkbox" name="consent" required ${u.consentAt?'checked':''}>Acepto el tratamiento de mis datos para gestionar mi formación y certificados.</label><p class="error" role="alert"></p><button class="btn">Guardar perfil</button></form></div>`;}
function help(){return heading('TE ACOMPAÑAMOS','Resuelve tus dudas.','Lo esencial para aprovechar tu campus.')+`<div class="panel">${[['¿Cómo ingreso?','Pulsa Ingresar al campus y escribe tu correo autorizado. Recibirás un código de un solo uso, válido por diez minutos. Si no llega, revisa el correo no deseado o consulta con el administrador.'],['¿Cómo apruebo un curso?','Inscríbete, estudia cada lección, marca el contenido completado y presenta la evaluación. La ficha muestra el porcentaje mínimo de aprobación.'],['¿Qué pasa si no apruebo?','Puedes repasar los contenidos y volver a intentarlo hasta el límite diario indicado en la evaluación. Tus intentos quedan registrados.'],['¿Cuándo llega mi certificado?','Al aprobar, el certificado queda registrado. El envío se procesa periódicamente; si hay un error o se agota la cuota de correo de Google, se reintentará. También puedes descargar el PDF en Certificaciones.'],['¿Puedo seguir desde otro dispositivo?','Sí. En el campus conectado, ingresa con el mismo correo para recuperar tu avance. La demostración guarda los datos solo en este navegador.'],['¿Qué puedo adjuntar a un curso?','Los administradores pueden añadir enlaces HTTPS a videos, documentos de Drive, presentaciones y otros recursos. El propietario debe dar a los estudiantes los permisos de lectura necesarios.'],['¿Qué acredita un certificado?','Acredita la aprobación del curso interno indicado. Su alcance depende de los contenidos y criterios definidos por la empresa. Los certificados de demostración no tienen validez institucional.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">Sin registros para mostrar.</td></tr>`}</tbody></table></div>`;}
async function render(){const ver=++loadVersion;chrome();document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');const [page='inicio',raw='']=location.hash.slice(1).split('/');let id;try{id=decodeURIComponent(raw);}catch{id='';}if(page==='admin'){if(!me||me.user.role!=='admin'){$('#main').innerHTML=requireLogin();return;}$('#main').innerHTML=heading('ADMINISTRACIÓN','Cargando información…');try{admin=await api('adminData');if(ver!==loadVersion)return;$('#main').innerHTML=adminPage();}catch(e){$('#main').innerHTML=empty('No se pudo cargar.',esc(e.message),btn('Reintentar','reload'));}return;}
 const views={inicio:home,oferta:offer,'mis-cursos':myCourses,curso:()=>coursePage(id),certificados:certificates,rutas:routes,biblioteca:library,verificar:()=>verifyPage(id),perfil:profile,ayuda:help};$('#main').innerHTML=(views[page]||home)();if(page==='oferta')filterCourses();if(page==='verificar'&&id)$('#verify-form').requestSubmit();window.scrollTo(0,0);}
function openDialog(html){$('#dialog').classList.remove('resource-dialog','certificate-dialog');$('#dialog-content').innerHTML=`<div class="dialog-head"><h2>Bienvenido a tu campus</h2><button class="icon-button" data-action="close" aria-label="Cerrar">✕</button></div>`+html;$('#dialog').showModal();}
function login(){if(UC_CONFIG.demo){openDialog('<div class="notice">Prueba el campus con datos ficticios. Esta demostración no envía correos ni genera certificados institucionales.</div><p>Elige el perfil que quieres explorar:</p><div class="dialog-actions">'+btn('Soy estudiante','demo-login','data-role="student"')+btn('Soy administrador','demo-login','data-role="admin"','secondary')+'</div>');return;}openDialog(`<p class="muted">Recibe un código en tu correo autorizado. No necesitas crear una contraseña.</p><form id="login-form">${field('email','Correo electrónico','','email','required autocomplete="email"')}<p class="error" role="alert"></p><button class="btn">Enviar código de acceso</button></form>`);}
async function authenticated(result){token=result.token;sessionStorage.setItem('xpanzia_token_v1',token);$('#dialog').close();await refresh();if(!result.user.name)location.hash='perfil';else await render();toast('Sesión iniciada.');}
function adminPage(){return heading('GESTIÓN DEL CAMPUS','Administración','Organiza la formación y acompaña el avance de tu equipo.')+`<div class="tabs" role="navigation" aria-label="Secciones de administración">${[['resumen','Indicadores'],['cursos','Cursos'],['rutas','Rutas'],['personas','Personas'],['certificados','Certificados'],['ajustes','Configuración']].map(([id,t])=>`<button data-action="admin-tab" data-tab="${id}" class="${id===adminTab?'active':''}">${t}</button>`).join('')}</div><div id="admin-content">${adminContent()}</div>`;}
function adminContent(){if(adminTab==='resumen')return dashboard();if(adminTab==='cursos')return `<div class="section-head"><h2>Oferta académica</h2>${btn('+ Crear curso','new-course')}</div>${table(['Curso','Escuela','Estado','Acciones'],admin.courses.map(c=>[esc(c.title),esc(c.school),tag(c.published?'Publicado':'Borrador',c.published?'green':''),btn('Editar','edit-course',`data-id="${esc(c.id)}"`,'secondary small')+' '+btn('Duplicar','duplicate-course',`data-id="${esc(c.id)}"`,'secondary small')]))}`;
 if(adminTab==='rutas')return `<div class="section-head"><h2>Rutas de aprendizaje</h2>${btn('+ Crear ruta','new-route')}</div>${table(['Ruta','Cursos','Estado','Acciones'],admin.routes.map(r=>[esc(r.title),r.courseIds.length,tag(r.published?'Publicada':'Borrador'),btn('Editar','edit-route',`data-id="${esc(r.id)}"`,'secondary small')]))}`;
 if(adminTab==='personas')return `<div class="panel"><h2>Autorizar estudiantes</h2><p class="muted">Agrega correos separados por comas o saltos de línea. Cada persona podrá solicitar su código de acceso. Esta acción no envía invitaciones.</p><form id="invite-form">${textField('emails','Correos autorizados','','required')}<button class="btn">Autorizar correos</button><p class="error" role="alert"></p></form><p class="small muted">${admin.invitations.length} correos autorizados individualmente.</p></div>${table(['Nombre','Correo','Área','Estado','Acción'],admin.users.map(u=>[esc(u.name||'Perfil pendiente'),esc(u.email),esc(u.area),tag(u.active===false?'Inactivo':'Activo',u.active===false?'red':'green'),u.id===me.user.id?'Mi cuenta':btn(u.active===false?'Activar':'Desactivar','toggle-user',`data-id="${esc(u.id)}" data-active="${u.active===false}"`,'secondary small')]))}`;
 if(adminTab==='certificados')return `<div class="notice blue">Los envíos pendientes se procesan automáticamente. Puedes consultar el detalle de un error y reprogramar su reintento. Revocar un certificado invalida su verificación.</div>${table(['Titular / Curso','Código','Estado','Correo','Acciones'],admin.certificates.map(c=>[esc(c.name)+'<br><span class="muted">'+esc(c.title)+'</span>',esc(c.code),tag(c.revoked?'Revocado':'Vigente',c.revoked?'red':'green'),esc(({sent:'Enviado',pending:'Pendiente',error:'Error',demo:'Demostración'})[c.mailStatus]||c.mailStatus)+(c.error?'<br><span title="'+esc(c.error)+'">'+esc(c.error.slice(0,100))+'</span>':''),c.revoked?'':btn('Revocar','revoke',`data-id="${esc(c.id)}"`,'secondary small')+(c.mailStatus==='error'?' '+btn('Reintentar','retry-mail',`data-id="${esc(c.id)}"`,'secondary small'):'')]))}`;
 const s=admin.settings;return `<div class="panel editor-width"><h2>Identidad y reglas del campus</h2><form id="settings-form"><div class="form-grid">${field('company','Nombre de la empresa',s.company,'text','required maxlength="150"')}${field('signer','Responsable institucional del certificado',s.signer,'text','required maxlength="150"')}${field('portalUrl','Dirección pública del campus',s.portalUrl,'url','required placeholder="https://usuario.github.io/universidad/"')}${field('maxAttempts','Intentos por curso al día (UTC)',s.maxAttempts,'number','required min="1" max="20"')}</div>${textField('privacy','Información de tratamiento de datos',s.privacy,'required')}<p class="error" role="alert"></p><button class="btn">Guardar configuración</button></form></div>${UC_CONFIG.demo?`<div class="panel"><h3>Restablecer la demostración</h3><p class="muted">Elimina los datos ficticios guardados en este navegador.</p>${btn('Restablecer demo','reset-demo','','secondary')}</div>`:''}`;}
function dashboard(){const select=(key,label,values)=>`<select class="report-filter" id="report-${key}" aria-label="${label}"><option value="">${label}</option>${[...new Set(values.filter(Boolean))].sort().map(v=>`<option>${esc(v)}</option>`).join('')}</select>`;return `<div class="filters">${['company','area','position','city'].map((k,i)=>select(k,['Todas las empresas','Todas las áreas','Todos los cargos','Todas las ciudades'][i],admin.users.map(u=>u[k]))).join('')}<select class="report-filter" id="report-course" aria-label="Curso"><option value="">Todos los cursos</option>${admin.courses.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select><select class="report-filter" id="report-status" aria-label="Estado"><option value="">Todos los estados</option><option>Aprobado</option><option>Pendiente</option><option>No aprobado</option></select><label>Desde<input class="report-filter" id="report-from" type="date"></label><label>Hasta<input class="report-filter" id="report-to" type="date"></label></div><div id="report-content"></div>`;}
function reportRows(){const val=id=>$('#report-'+id)?.value||'';return admin.enrollments.flatMap(e=>{const u=admin.users.find(x=>x.id===e.userId)||{},c=admin.courses.find(x=>x.id===e.courseId)||{};if(['company','area','position','city'].some(k=>val(k)&&val(k)!==u[k])||val('course')&&val('course')!==e.courseId)return [];const all=admin.attempts.filter(a=>a.userId===e.userId&&a.courseId===e.courseId).sort((a,b)=>a.date.localeCompare(b.date));const inRange=all.filter(a=>(!val('from')||a.date.slice(0,10)>=val('from'))&&(!val('to')||a.date.slice(0,10)<=val('to')));const a=inRange.find(a=>a.passed)||inRange[inRange.length-1];const day=(a?.date||e.date).slice(0,10);if(val('from')&&day<val('from')||val('to')&&day>val('to'))return [];const status=a?.passed?'Aprobado':a?'No aprobado':'Pendiente';if(val('status')&&val('status')!==status)return [];return [{name:u.name||u.email,email:u.email,document:u.document,company:u.company,area:u.area,position:u.position,city:u.city,course:c.title||e.courseId,date:a?.date||e.date,score:a?.score??'',status,attempts:inRange.length,userId:u.id,courseId:e.courseId}];});}
function renderReport(){if(!$('#report-content'))return;const rows=reportRows(),ap=rows.filter(r=>r.status==='Aprobado').length,attempted=rows.filter(r=>r.status!=='Pendiente').length;$('#report-content').innerHTML=`<div class="stats">${stat('Personas en el filtro',new Set(rows.map(r=>r.userId)).size,'◎')}${stat('Inscripciones aprobadas',ap,'✓')}${stat('Aprobación evaluados',attempted?Math.round(ap/attempted*100)+'%':'—','%')}${stat('Inscripciones pendientes',rows.filter(r=>r.status!=='Aprobado').length,'◷')}</div><div class="panel"><h2>Avance por escuela</h2>${schools.map(([s])=>{const selected=rows.filter(r=>admin.courses.find(c=>c.id===r.courseId)?.school===s),pass=selected.filter(r=>r.status==='Aprobado').length,pct=selected.length?Math.round(pass/selected.length*100):0;return `<div class="bar-row"><span>${s}</span><div class="progress"><span style="width:${pct}%"></span></div><b>${pct}%</b></div>`;}).join('')}</div><div class="section-head"><div><h2>Seguimiento de formación</h2><p class="small muted" style="margin:8px 0 0">${admin.courses.filter(c=>c.published).length} cursos publicados · ${admin.certificates.filter(c=>!c.revoked).length} certificados vigentes en todo el campus. El periodo filtra evaluaciones o inscripciones sin evaluación.</p></div>${btn('Descargar CSV','export','','secondary')}</div>${table(['Persona','Área','Curso','Fecha','Nota','Estado','Intentos'],rows.map(r=>[esc(r.name),esc(r.area),esc(r.course),date(r.date),r.score===''?'—':r.score+'%',tag(r.status,r.status==='Aprobado'?'green':'gold'),r.attempts]))}`;}
function editCourse(id,duplicate=false){editing=id?structuredClone(admin.courses.find(c=>c.id===id)):{id:'',title:'',school:'Calidad',description:'',hours:1,level:'Básico',passScore:80,published:false,lessons:[{id:crypto.randomUUID(),title:'',body:'',url:'',type:'Lectura'}],quiz:[{id:crypto.randomUUID(),text:'',options:['','','',''],correct:0}]};if(duplicate){editing.id='';editing.title+=' (copia)';editing.published=false;}renderEditor();}
function renderEditor(){const c=editing;$('#admin-content').innerHTML=`<div class="editor-width"><div class="section-head"><h2>${c.id?'Editar curso':'Crear curso'}</h2>${btn('Cancelar','cancel-editor','','secondary')}</div><form id="course-form"><div class="panel"><div class="form-grid">${field('title','Nombre del curso',c.title,'text','required maxlength="150"')}<div class="field"><label for="school">Escuela</label><select name="school" id="school">${schools.map(([s])=>`<option ${c.school===s?'selected':''}>${s}</option>`).join('')}</select></div>${field('hours','Duración en horas',c.hours,'number','min="0.1" max="1000" step="0.1" required')}${field('level','Nivel',c.level,'text','required')}${field('passScore','Nota mínima (%)',c.passScore,'number','min="1" max="100" required')}</div>${textField('description','Descripción del curso',c.description,'required maxlength="2500"')}<label><input type="checkbox" name="published" ${c.published?'checked':''}>Publicar en la oferta académica</label></div><div class="section-head"><h2>Lecciones</h2>${btn('+ Añadir lección','add-lesson','type="button"','secondary')}</div><p class="muted small">Escribe el contenido y, si lo necesitas, añade un enlace a Drive, YouTube o un recurso con acceso autorizado.</p>${c.lessons.map((l,i)=>`<section class="editor-item lesson-editor" data-id="${esc(l.id)}"><h3>Lección ${i+1} ${btn('Eliminar','remove-lesson',`type="button" data-index="${i}"`,'secondary small')}</h3>${field('lt'+i,'Título',l.title,'text','required maxlength="150"')}${textField('lb'+i,'Contenido',l.body,'required maxlength="12000"')}<div class="form-grid">${field('ly'+i,'Tipo de recurso',l.type,'text','required placeholder="Lectura, Video, PDF…"')}${field('lu'+i,'Enlace opcional (https://)',l.url,'url')}</div></section>`).join('')}<div class="section-head"><h2>Evaluación final</h2>${btn('+ Añadir pregunta','add-question','type="button"','secondary')}</div>${c.quiz.map((q,i)=>`<section class="editor-item question-editor" data-id="${esc(q.id)}"><h3>Pregunta ${i+1} ${btn('Eliminar','remove-question',`type="button" data-index="${i}"`,'secondary small')}</h3>${field('qt'+i,'Enunciado',q.text,'text','required maxlength="1000"')}<div class="form-grid">${q.options.map((o,j)=>field('qo'+i+'_'+j,'Opción '+(j+1),o,'text','required maxlength="500"')).join('')}</div><div class="field"><label for="qc${i}">Respuesta correcta</label><select name="qc${i}" id="qc${i}">${q.options.map((o,j)=>`<option value="${j}" ${q.correct===j?'selected':''}>Opción ${j+1}</option>`).join('')}</select></div></section>`).join('')}<p class="error" role="alert"></p><div class="dialog-actions"><button class="btn" type="submit">Guardar curso</button>${btn('Cancelar','cancel-editor','type="button"','secondary')}</div></form></div>`;}
function collectEditor(){const f=$('#course-form'),d=new FormData(f);Object.assign(editing,{title:d.get('title'),school:d.get('school'),description:d.get('description'),hours:+d.get('hours'),level:d.get('level'),passScore:+d.get('passScore'),published:d.has('published')});editing.lessons=editing.lessons.map((l,i)=>({...l,title:d.get('lt'+i),body:d.get('lb'+i),type:d.get('ly'+i),url:d.get('lu'+i)}));editing.quiz=editing.quiz.map((q,i)=>({...q,text:d.get('qt'+i),options:q.options.map((_,j)=>d.get('qo'+i+'_'+j)),correct:+d.get('qc'+i)}));return editing;}
function editRoute(id){const r=admin.routes.find(x=>x.id===id)||{id:'',title:'',description:'',courseIds:[],published:false};$('#admin-content').innerHTML=`<div class="panel editor-width"><h2>${r.id?'Editar ruta':'Crear ruta'}</h2><form id="route-form" data-id="${esc(r.id)}">${field('title','Nombre de la ruta',r.title,'text','required')}${textField('description','Descripción',r.description)}<h3>Cursos de la ruta</h3>${admin.courses.map(c=>`<label><input type="checkbox" name="courseIds" value="${esc(c.id)}" ${r.courseIds.includes(c.id)?'checked':''}>${esc(c.title)} ${c.published?'':'(borrador)'}</label>`).join('')}<label style="margin-top:25px"><input type="checkbox" name="published" ${r.published?'checked':''}>Publicar ruta</label><p class="error" role="alert"></p><div class="dialog-actions"><button class="btn">Guardar ruta</button>${btn('Cancelar','cancel-editor','type="button"','secondary')}</div></form></div>`;}
function downloadBlob(blob,name){const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function exportReport(){const rows=reportRows();const cols=[['name','Nombre'],['document','Documento'],['email','Correo'],['company','Empresa'],['area','Área'],['position','Cargo'],['city','Ciudad'],['course','Curso'],['date','Fecha'],['score','Nota'],['status','Estado'],['attempts','Intentos']];const cell=v=>'"'+String(v??'').replace(/^[\s]*[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const csv=[cols.map(c=>cell(c[1])).join(';'),...rows.map(r=>cols.map(c=>cell(r[c[0]])).join(';'))].join('\r\n');downloadBlob(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),'Seguimiento_Universidad_'+new Date().toISOString().slice(0,10)+'.csv');}
function certificateMarkup(c,demo=false){const warning=c.revoked?'CERTIFICADO REVOCADO':demo?'DEMOSTRACIÓN · SIN VALIDEZ INSTITUCIONAL':'';return `<div class="diploma-wrap"><article class="diploma" aria-label="Vista previa del certificado"><img class="diploma-logo" src="assets/xpanzia-logo.jpg" alt="Xpanzia Group"><img class="diploma-signature-logo" src="assets/xpanzia-logo.jpg" alt="Firma institucional Xpanzia Group">${UC_CERTIFICATE.layout(c).map(b=>`<div class="diploma-text" style="left:${b.x/7.2}%;top:${b.y/4.05}%;width:${b.w/7.2}%;height:${b.h/4.05}%;font-size:${b.size/7.2}cqw;font-family:${b.font},${b.font==='Georgia'?'serif':'sans-serif'};color:${b.color};font-weight:${b.bold?700:400}">${b.link?`<a href="${safeUrl(b.link)}" target="_blank" rel="noopener">${esc(b.text)}</a>`:esc(b.text)}</div>`).join('')}<div class="diploma-rule"></div><div class="diploma-signature"></div>${warning?`<div class="diploma-warning">${warning}</div>`:''}</article></div>`;}
function previewCertificate(id){const c=me.certificates.find(x=>x.id===id);if(!c)return;openDialog(certificateMarkup(c,UC_CONFIG.demo)+`<div class="dialog-actions">${!c.revoked?btn(UC_CONFIG.demo?'Imprimir ejemplo':'Descargar PDF',UC_CONFIG.demo?'print':'download',`data-id="${esc(c.id)}"`):''}<p class="small muted">${UC_CONFIG.demo?'Ejemplo sin validez institucional.':'El PDF conserva los datos registrados al aprobar.'}</p></div>`);$('#dialog').classList.add('certificate-dialog');$('#dialog-content h2').textContent='Tu certificado';}
async function downloadCert(id){const c=me.certificates.find(x=>x.id===id);if(UC_CONFIG.demo){$('#main').innerHTML=`<div class="no-print row" style="margin-bottom:25px"><a class="btn secondary" href="#certificados">← Mis certificados</a>${btn('Imprimir / guardar PDF','print')}</div>`+certificateMarkup(c,true);return;}const d=await api('downloadCertificate',{id});const binary=atob(d.base64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));downloadBlob(new Blob([bytes],{type:'application/pdf'}),d.filename);}
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(b.type!=='submit')event.preventDefault();if(b.disabled)return;b.disabled=true;try{
 switch(action){
 case 'preview-resource':{const l=catalog.courses.find(c=>c.id===b.dataset.course)?.lessons.find(l=>l.id===b.dataset.lesson);if(l){openDialog(resourceViewer(l.url,l.title));$('#dialog').classList.add('resource-dialog');$('#dialog-content h2').textContent=l.title;}break;}
 case 'login':login();break;case 'close':$('#dialog').close();break;
 case 'demo-login':await authenticated(await api('demoLogin',{role:b.dataset.role}));break;
 case 'logout':await api('logout');token='';me=null;sessionStorage.removeItem('xpanzia_token_v1');location.hash='inicio';await render();break;
 case 'school':filterSchool=b.dataset.school;location.hash='oferta';if($('#school-filter')){$('#school-filter').value=filterSchool;filterCourses();}break;
 case 'enroll':if(!me){login();break;}if(!me.user.name||!me.user.consentAt){location.hash='perfil';toast('Completa tu perfil antes de inscribirte.');break;}upsert(me.enrollments,await api('enroll',{courseId:b.dataset.id}));await render();toast('¡Ya estás inscrito!');break;
 case 'lesson':lessonIndex=+b.dataset.index;await render();break;
 case 'previous':lessonIndex--;await render();break;case 'mycourses':location.hash='mis-cursos';break;
 case 'complete':{const currentHash=location.hash,index=lessonIndex,e=me.enrollments.find(x=>x.courseId===b.dataset.course);if(!e?.completed.includes(b.dataset.lesson))upsert(me.enrollments,await api('completeLesson',{courseId:b.dataset.course,lessonId:b.dataset.lesson}));if(location.hash===currentHash&&lessonIndex===index){lessonIndex++;await render();}break;}
 case 'preview-certificate':previewCertificate(b.dataset.id);break;
 case 'download':await downloadCert(b.dataset.id);break;case 'print':window.print();break;
 case 'admin-tab':adminTab=b.dataset.tab;$('#main').innerHTML=adminPage();renderReport();break;
 case 'new-course':editCourse();break;case 'edit-course':editCourse(b.dataset.id);break;case 'duplicate-course':editCourse(b.dataset.id,true);break;
 case 'cancel-editor':editing=null;$('#main').innerHTML=adminPage();renderReport();break;
 case 'add-lesson':collectEditor();editing.lessons.push({id:crypto.randomUUID(),title:'',body:'',url:'',type:'Lectura'});renderEditor();break;
 case 'remove-lesson':if(editing.lessons.length===1)throw Error('El curso necesita al menos una lección.');collectEditor();editing.lessons.splice(+b.dataset.index,1);renderEditor();break;
 case 'add-question':collectEditor();editing.quiz.push({id:crypto.randomUUID(),text:'',options:['','','',''],correct:0});renderEditor();break;
 case 'remove-question':if(editing.quiz.length===1)throw Error('La evaluación necesita al menos una pregunta.');collectEditor();editing.quiz.splice(+b.dataset.index,1);renderEditor();break;
 case 'new-route':editRoute();break;case 'edit-route':editRoute(b.dataset.id);break;
 case 'toggle-user':if(!confirm(b.dataset.active==='true'?'¿Activar este usuario?':'¿Desactivar el acceso de este usuario?'))break;await api('setUserActive',{id:b.dataset.id,active:b.dataset.active==='true'});await render();break;
 case 'revoke':if(!confirm('¿Revocar este certificado? Su verificación pública mostrará que no es válido.'))break;await api('revokeCertificate',{id:b.dataset.id});await render();break;
 case 'retry-mail':await api('retryMail',{id:b.dataset.id});toast('Reintento programado.');await render();break;
 case 'export':exportReport();break;
 case 'reset-demo':if(confirm('¿Borrar los datos locales de demostración?'))UC_DEMO.reset();break;
 case 'reload':await boot();break;
 }
 }catch(e){toast(e.message);}finally{b.disabled=false;}});
document.addEventListener('submit',async event=>{const f=event.target;if(!(f instanceof HTMLFormElement))return;event.preventDefault();const submit=f.querySelector('button[type="submit"],button:not([type])');if(submit?.disabled)return;if(submit)submit.disabled=true;const err=f.querySelector('.error');if(err)err.textContent='';const d=new FormData(f);try{
 if(f.id==='login-form'){const email=d.get('email'),result=await api('requestCode',{email});$('#dialog-content').innerHTML=`<div class="dialog-head"><h2>Revisa tu correo</h2>${btn('✕','close','aria-label="Cerrar"','secondary small')}</div><p>${esc(result.message)}</p><form id="code-form" data-email="${esc(email)}" data-challenge="${esc(result.challenge)}">${field('otp','Código de ocho dígitos','','text','required pattern="[0-9]{8}" inputmode="numeric" maxlength="8" autocomplete="one-time-code"')}<p class="error" role="alert"></p><button class="btn">Ingresar</button></form><div class="dialog-actions">${btn('Usar otro correo / solicitar nuevo código','login','','link')}</div>`;$('#otp').focus();}
 else if(f.id==='code-form'){await authenticated(await api('verifyCode',{email:f.dataset.email,challenge:f.dataset.challenge,code:d.get('otp')}));}
 else if(f.id==='profile-form'){me.user=await api('saveProfile',{...Object.fromEntries(d),consent:d.has('consent')});chrome();toast('Perfil actualizado.');location.hash='mis-cursos';}
 else if(f.id==='quiz-form'){const c=catalog.courses.find(x=>x.id===f.dataset.course);const result=await api('submitQuiz',{courseId:c.id,answers:c.quiz.map((_,i)=>+d.get('q'+i)),requestId:f.dataset.request});await refreshProfile();if(result.passed){await render();toast('¡Aprobaste! Tu certificado está registrado.');}else{$('#main').innerHTML=heading('EVALUACIÓN',esc(c.title))+`<div class="panel" style="text-align:center"><h2>Un intento más para seguir aprendiendo.</h2><div class="score" style="color:#ad7b21">${result.score}%</div><p>Necesitas ${c.passScore}% para aprobar. Tu intento quedó registrado. Repasa las lecciones antes de volver a presentar.</p>${btn('Repasar el curso','lesson','data-index="0"')}</div>`;}}
 else if(f.id==='verify-form'){const box=$('#verification-result');box.innerHTML='<div class="panel">Verificando…</div>';try{const c=await api('verifyCertificate',{code:String(d.get('code')).trim().toUpperCase()});box.innerHTML=`<div class="panel" style="max-width:720px">${tag(c.revoked?'CERTIFICADO REVOCADO':UC_CONFIG.demo?'DEMOSTRACIÓN SIN VALIDEZ':'CERTIFICADO VÁLIDO',c.revoked?'red':UC_CONFIG.demo?'gold':'green')}<h2 style="margin-top:22px">${esc(c.title)}</h2><p><strong>${esc(c.name)}</strong></p><p class="muted">${esc(c.company)} · ${c.hours} horas · ${date(c.date)}</p><code>${esc(c.code)}</code></div>`;}catch(e){box.innerHTML=`<div class="notice" role="alert">${esc(e.message)}</div>`;}}
 else if(f.id==='course-form'){await api('saveCourse',collectEditor());editing=null;catalog=await api('catalog');await render();toast('Curso guardado.');}
 else if(f.id==='route-form'){const courseIds=d.getAll('courseIds');if(!courseIds.length)throw Error('Selecciona al menos un curso.');await api('saveRoute',{id:f.dataset.id,title:d.get('title'),description:d.get('description'),courseIds,published:d.has('published')});catalog=await api('catalog');await render();toast('Ruta guardada.');}
 else if(f.id==='settings-form'){catalog.settings=await api('saveSettings',{...Object.fromEntries(d),maxAttempts:+d.get('maxAttempts')});await render();toast('Configuración guardada.');}
 else if(f.id==='invite-form'){await api('invite',{emails:d.get('emails')});await render();toast('Correos autorizados.');}
 }catch(e){if(err&&err.isConnected)err.textContent=e.message;else toast(e.message);}finally{if(submit)submit.disabled=false;}});
document.addEventListener('input',e=>{if(e.target.id==='course-search')filterCourses();if(e.target.id==='library-search'){let n=0;$$('.resource').forEach(x=>{x.hidden=!x.dataset.search.includes(e.target.value.toLowerCase());if(!x.hidden)n++;});$('#library-empty').hidden=!!n;}});
document.addEventListener('change',e=>{if(e.target.id==='school-filter')filterCourses();if(e.target.classList.contains('report-filter'))renderReport();});
$('#menu').addEventListener('click',()=>{document.body.classList.toggle('menu-open');$('#menu').setAttribute('aria-expanded',document.body.classList.contains('menu-open'));});
document.addEventListener('click',e=>{if(document.body.classList.contains('menu-open')&&!e.target.closest('#sidebar,#menu')){document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');}});
window.addEventListener('hashchange',()=>render().then(renderReport));
async function boot(){try{await refresh();await render();renderReport();}catch(e){$('#main').innerHTML=empty('No pudimos conectar con el campus.',esc(e.message),btn('Reintentar','reload'));}}
boot();


$('#dialog').addEventListener('close',()=>{$('#dialog-content').replaceChildren();$('#dialog').classList.remove('resource-dialog','certificate-dialog');});

// Convert supported links to in-campus viewers; never embed arbitrary HTML.
function resourceSource(value){
 let u;try{u=new URL(value);}catch{return null;}
 if(u.protocol!=='https:'||u.username||u.password)return null;
 const host=u.hostname.toLowerCase(),parts=u.pathname.split('/').filter(Boolean);
 if(['youtube.com','www.youtube.com','m.youtube.com','youtu.be','www.youtube-nocookie.com'].includes(host)){
  const id=host==='youtu.be'?parts[0]:['embed','shorts','live'].includes(parts[0])?parts[1]:u.searchParams.get('v');
  if(!/^[A-Za-z0-9_-]{11}$/.test(id||''))return null;
  return {kind:'frame',video:true,url:'https://www.youtube-nocookie.com/embed/'+id};
 }
 if(host==='drive.google.com'){
  const match=u.pathname.match(/\/file\/d\/([\w-]+)/),id=match?.[1]||u.searchParams.get('id');
  if(!/^[\w-]+$/.test(id||''))return null;
  const preview=new URL('https://drive.google.com/file/d/'+id+'/preview');
  if(u.searchParams.has('resourcekey'))preview.searchParams.set('resourcekey',u.searchParams.get('resourcekey'));
  return {kind:'frame',url:preview.href};
 }
 if(host==='docs.google.com'){
  const m=u.pathname.match(/^\/(document|spreadsheets|presentation)\/d\/(?:e\/)?([\w-]+)(\/.*)?$/);
  if(m){const published=u.pathname.includes('/d/e/');return {kind:'frame',url:u.origin+'/'+m[1]+'/d/'+(published?'e/':'')+m[2]+'/'+(published?(m[1]==='spreadsheets'?'pubhtml':m[1]==='presentation'?'embed':'pub'):'preview')};}
 }
 const ext=u.pathname.split('.').pop().toLowerCase();
 const kind=['mp4','webm','ogv'].includes(ext)?'video':['mp3','wav','ogg','m4a'].includes(ext)?'audio':['png','jpg','jpeg','gif','webp','avif'].includes(ext)?'image':ext==='pdf'?'frame':null;
 return kind?{kind,url:u.href}:null;
}
function resourceViewer(url,title){
 const source=resourceSource(url),label=esc(title||'Material del curso');
 let content='';
 if(source){const src=esc(source.url);
  if(source.kind==='video')content=`<video controls playsinline preload="metadata" aria-label="${label}" src="${src}"></video>`;
  else if(source.kind==='audio')content=`<audio controls preload="metadata" aria-label="${label}" src="${src}"></audio>`;
  else if(source.kind==='image')content=`<img loading="lazy" src="${src}" alt="${label}">`;
  else content=`<iframe class="${source.video?'video-frame':''}" src="${src}" title="${label}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" sandbox="allow-scripts allow-same-origin allow-forms allow-presentation" allow="fullscreen; encrypted-media; picture-in-picture" allowfullscreen></iframe>`;
 }
 return `<section class="resource-viewer" aria-label="Material del curso">${content||'<p>Este enlace no tiene una vista previa compatible. Para verlo aquí, utiliza un archivo de Drive, YouTube, PDF, imagen, audio o video directo.</p>'}<details><summary>${source?'¿No se muestra el material?':'Opciones del recurso'}</summary><p>El archivo debe permitir acceso a tu cuenta y visualización integrada. Algunos proveedores bloquean esta vista. Para documentos de Office, utiliza su enlace de Google Drive.</p>${safeUrl(url)!=='#'?`<a href="${safeUrl(url)}" target="_blank" rel="noopener noreferrer">Abrir original si lo necesitas ↗</a>`:''}</details></section>`;
}

